server:
  port: 4003

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: connector-service-route
              uri: http://connect-connector-service:4001
              predicates:
                - Path=/api/connectors/**
              filters:
                - StripPrefix=1

            - id: auth-service-route
              uri: http://connect-auth-service:4000
              predicates:
                - Path=/auth/**
              filters:
                - name: RewritePath
                  args:
                    regexp: "/auth/(?<segment>.*)"
                    replacement: "/auth/public/${segment}"