server:
  port: 4003

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: connector-service-route
              uri: http://connect-connector-service:4001
              predicates:
                - Path=/api/connectors/**
              filters:
                - StripPrefix=1

            - id: trip-service-route
              uri: http://connect-trip-service:4002
              predicates:
                - Path=/api/trips/**
              filters:
                - StripPrefix=1

            - id: auth-service-route
              uri: http://connect-auth-service:4000
              predicates:
                - Path=/api/auth/**
              filters:
                - name: RewritePath
                  args:
                    regexp: "/api/auth/(?<segment>.*)"
                    replacement: "/auth/public/${segment}"

            - id: discovery-service-route
              uri: http://connect-discovery-service:4004
              predicates:
                - Path=/api/discover/**
              filters:
                - StripPrefix=1